// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdrcgloswtfdovoucvqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkcmNnbG9zd3RmZG92b3VjdnFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NjkzNTQsImV4cCI6MjA3MjQ0NTM1NH0.K-53apaVPBtuxfNDLLGwQRB96jGlKbZDdFj_lciUaGE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});